#!/bin/bash

# ============================================================================
# BHARATPRINT DEPLOYMENT - EXACT COMMANDS TO RUN
# ============================================================================
# Copy and paste these commands exactly as shown to deploy BharatPrint
# ============================================================================

echo "🚀 BharatPrint Deployment Helper"
echo "=================================="
echo ""
echo "This script shows the exact commands to deploy BharatPrint"
echo ""

# STEP 1: Verify Files
echo "✅ STEP 1: Verify all deployment files exist"
echo "============================================"
echo ""
echo "Run these commands to verify files are created:"
echo ""
echo "cd /home/arjun/Downloads/BHARATPRINTmain2"
echo ""
echo "# Check configuration files"
echo "ls -lh netlify.toml"
echo "ls -lh frontend/.env.production"
echo "ls -lh Procfile"
echo "ls -lh render.yaml"
echo "ls -lh backend/runtime.txt"
echo ""

# STEP 2: Push to GitHub
echo "✅ STEP 2: Push configuration to GitHub"
echo "========================================"
echo ""
echo "Run these commands to push to GitHub:"
echo ""
echo "cd /home/arjun/Downloads/BHARATPRINTmain2"
echo ""
echo "# Add all deployment files"
echo "git add netlify.toml frontend/.env.production Procfile render.yaml backend/runtime.txt"
echo "git add DEPLOYMENT_*.md ENVIRONMENT_VARIABLES.md DEPLOYMENT_SUMMARY.txt START_HERE_DEPLOYMENT.md"
echo ""
echo "# Commit"
echo 'git commit -m "deployment: Add complete Netlify and Render.com deployment package"'
echo ""
echo "# Push to GitHub"
echo "git push origin main"
echo ""
echo "# Verify push"
echo "git log --oneline | head -5"
echo ""

# STEP 3: Frontend Deployment
echo "✅ STEP 3: Deploy Frontend to Netlify"
echo "======================================"
echo ""
echo "1. Go to: https://app.netlify.com"
echo "2. Click: 'Add new site' → 'Import an existing project'"
echo "3. Choose: GitHub → authorize"
echo "4. Select: 'bharatprint2' repository"
echo "5. Build settings are auto-configured from netlify.toml"
echo "6. Click: 'Deploy'"
echo ""
echo "Wait 3-5 minutes for build..."
echo ""
echo "After deployment, note your URL:"
echo "   https://bharatprint-XXXXX.netlify.app"
echo ""

# STEP 4: Backend Deployment
echo "✅ STEP 4: Deploy Backend to Render.com"
echo "========================================"
echo ""
echo "1. Go to: https://dashboard.render.com"
echo "2. Click: 'New +' → 'Web Service'"
echo "3. Connect GitHub and select: 'bharatprint2'"
echo "4. Service name: 'bharatprint-backend'"
echo ""
echo "BEFORE deploying, add these Environment Variables:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Where to get values (see ENVIRONMENT_VARIABLES.md for details):"
echo ""
echo "SUPABASE_URL"
echo "  From: https://app.supabase.com → Settings → API"
echo "  Copy: Project URL (e.g., https://xxx.supabase.co)"
echo ""
echo "SUPABASE_KEY"
echo "  From: https://app.supabase.com → Settings → API"
echo "  Copy: anon public key (starts with eyJhbGc...)"
echo ""
echo "SUPABASE_SERVICE_KEY"
echo "  From: https://app.supabase.com → Settings → API"
echo "  Copy: service_role key (starts with eyJhbGc...)"
echo ""
echo "JWT_SECRET"
echo "  From: Your local backend/.env file"
echo "  Copy: The JWT_SECRET value"
echo ""
echo "FIREBASE_CREDENTIALS_PATH"
echo "  Value: ./firebase-service-account-key.json"
echo ""
echo "CORS_ORIGINS"
echo "  Value: Your Netlify URL from Step 3"
echo "  Format: https://bharatprint-XXXXX.netlify.app"
echo ""
echo "Add all variables, then click 'Create Web Service'"
echo ""
echo "After deployment, note your backend URL:"
echo "   https://bharatprint-backend.onrender.com"
echo ""

# STEP 5: Testing
echo "✅ STEP 5: Test Deployment"
echo "=========================="
echo ""
echo "Test 1: Frontend loads"
echo "  Visit: https://bharatprint-XXXXX.netlify.app"
echo "  Should see: BharatPrint homepage"
echo ""
echo "Test 2: Backend accessible"
echo "  Visit: https://bharatprint-backend.onrender.com/docs"
echo "  Should see: Swagger API documentation"
echo ""
echo "Test 3: Communication works"
echo "  Open: Frontend in browser"
echo "  Open: DevTools (F12) → Network tab"
echo "  Action: Try login"
echo "  Verify: Requests go to onrender.com, no CORS errors"
echo ""
echo "Test 4: SMS-OTP flow"
echo "  Go: Signup page"
echo "  Enter: +91 9999999999"
echo "  Check: Firebase logs for SMS"
echo "  Verify: Can complete signup"
echo ""
echo "Test 5: Database"
echo "  Go: Supabase dashboard"
echo "  Check: Users table for new signup"
echo ""

# Documentation
echo "✅ DOCUMENTATION"
echo "==============="
echo ""
echo "For detailed instructions, read these files:"
echo ""
echo "START_HERE_DEPLOYMENT.md     ← Read this first!"
echo "DEPLOYMENT_GUIDE.md          ← Complete step-by-step guide"
echo "DEPLOYMENT_CHECKLIST.md      ← Quick reference"
echo "ENVIRONMENT_VARIABLES.md     ← Variable reference"
echo "DEPLOYMENT_READY.md          ← Quick overview"
echo ""

echo "✅ YOU'RE ALL SET!"
echo "=================="
echo ""
echo "Next step: Run the git push commands from Step 2 above"
echo ""
echo "Questions? Check the documentation files listed above."
echo ""
